Feature/user forum backend
LnuOup/LnuDormWatch pull request #21
Opened 2020-12-14 00:54 UTC by sergiynikon

2020-12-14 03:42 UTC, RomanNakonechnyi approved these changes

2020-12-14 14:38 UTC, AttFlederX approved these changes

2020-12-14 21:35 UTC, Meownjik commented on src/backend/LDW.Persistance/Context/ApplicationDbContext.cs
> +		public DbSet<ForumThreadReplyEntity> ForumThreadReplies { get; set; }
Where have the lines gone? (Куди все з'їхало?)

2020-12-14 21:36 UTC, Meownjik approved these changes

2020-12-15 22:12 UTC, sergiynikon commented on src/backend/LDW.Persistance/Context/ApplicationDbContext.cs
> +		public DbSet<ForumThreadReplyEntity> ForumThreadReplies { get; set; }
it github issue. In visual studio these lines are displayed normally with normal indentation

2020-12-16 09:49 UTC, Meownjik approved these changes
That's a bit annoying when you have 100500 files changed in one pull request

2020-12-16 11:22 UTC, AttFlederX requested changes
Fix foreign key issues before merging

2020-12-16 12:34 UTC, sergiynikon commented
> Fix foreign key issues before merging

done

2020-12-16 14:19 UTC, AttFlederX approved these changes

2020-12-16 19:50 UTC, merged